# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Akash Agrahari
tagline:             ' Blog | Music | Code'
description:         'blah'
url:                 http://frugalcoder.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Akash Agrahari
  url:               https://twitter.com/AA_isnowonline
  email:             akash.agrahari@gmail.com

# Custom vars
version:             1.1.1
